AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Bitespeed Identity Reconciliation Service

Parameters:
    SupabaseUrl:
        Type: String
        Description: Supabase project URL
        NoEcho: true
    SupabaseKey:
        Type: String
        Description: Supabase API key
        NoEcho: true
    UpstashRedisRestUrl:
        Type: String
        Description: Upstash Redis REST API URL
        NoEcho: true
    UpstashRedisRestToken:
        Type: String
        Description: Upstash Redis REST API token
        NoEcho: true

Globals:
    Function:
        Timeout: 15
        MemorySize: 256
        LoggingConfig:
            LogFormat: JSON
        Architectures:
            - x86_64
        Runtime: nodejs22.x

Resources:
    RestApiRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: apigateway.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: InvokeLambdaPolicy
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - lambda:InvokeFunction
                            Resource:
                                - !GetAtt IdentifyFunction.Arn

    IdentityAPI:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            DefinitionBody:
                Fn::Transform:
                    Name: AWS::Include
                    Parameters:
                        Location: ./api/backend-api.yaml

    IdentifyFunction:
        Type: AWS::Serverless::Function
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - app.ts
        Properties:
            CodeUri: src/identify/
            Handler: app.handler
            Environment:
                Variables:
                    SUPABASE_URL: !Ref SupabaseUrl
                    SUPABASE_KEY: !Ref SupabaseKey
                    UPSTASH_REDIS_REST_URL: !Ref UpstashRedisRestUrl
                    UPSTASH_REDIS_REST_TOKEN: !Ref UpstashRedisRestToken
            Policies:
                - Statement:
                      - Effect: Allow
                        Action:
                            - logs:CreateLogGroup
                            - logs:CreateLogStream
                            - logs:PutLogEvents
                        Resource: '*'

Outputs:
    IdentityApi:
        Description: URL of the API Gateway
        Value: !Sub 'https://${IdentityAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    IdentifyFunctionArn:
        Description: ARN of the Identify Lambda Function
        Value: !GetAtt IdentifyFunction.Arn
